language: node_js
node_js:
- '0.10'
addons:
  code_climate:
    repo_token:
      secure: K8WlINTzAcqpP1NtorthO+CGXMg0m2tAcBqIb9MSNPYz5pWVrfr9ARXKrX437ve3VXeczT39IIquce41EOdGwMjQ/VEKxl/+acuYA5vsgpHPQnsLSAUc5Ote65Y+grdtQFHqXu4eOoNRpXSWGSnpp8ecPCf/2DUiHs8XSfg1EEg=
before_install:
- npm install -g npm
- npm install -g codeclimate-test-reporter
install:
- npm install
script:
- npm run test
after_success:
- npm run cover-lcov
- codeclimate < ./coverage/lcov.info
deploy:
  provider: npm
  email: aymeric@beaumet.me
  api_key:
    secure: ctVR/CCImf65crS66QOTiM0TENRr+PEB0pP3KCZM5ovoxcuStdfU7TZjg90chKeEjFvU+YgtOS+1cMwCB0MOIqariDOrTW18siPlAF2W3EoMVc1OUwHXM24LHvKK2XMNxuuBeGxrMWnOL5N9ybo4DEgQZjPWZALh3YxMxWjMBQo=
  on:
    repo: captaindash/node-mention-api
    branch: master
    tags: true
